// frontend/src/components/pages/Forms.tsx
import styles from './forms.module.css';
import { FaGoogle, FaGithub, FaFacebook } from "react-icons/fa";

import React, { useRef, useEffect } from 'react';

const FormsComponent: React.FC = () => {

    const containerRef = useRef<HTMLDivElement>(null);
    const registerBtnRef = useRef<HTMLButtonElement>(null);
    const loginBtnRef = useRef<HTMLButtonElement>(null);

    useEffect(() => {
        const container = containerRef.current;
        const registerBtn = registerBtnRef.current;
        const loginBtn = loginBtnRef.current;

        registerBtn?.addEventListener('click', () => {
            container?.classList.add(styles.active);
        });

        loginBtn?.addEventListener('click', () => {
            container?.classList.remove(styles.active);
        });
    }, []);
  
    return (
        <main>
            <section className={styles.container} ref={containerRef} id="container">
                <div className={`${styles.signUp} ${styles.formContainer}`}>
                    <form>
                        <h1>Cadastre-se</h1>
                        <div className={styles.socialIcons}>
                            <a href="#"><FaGoogle /></a>
                            <a href="#"><FaGithub /></a>
                            <a href="#"><FaFacebook /></a>
                        </div>
                        <span>ou use seu e-mail para cadastro</span>
                        <input
                            type="text" placeholder="Nome de usuário" required
                        />
                        <input
                            type="email" placeholder="E-mail" required
                        />
                        <input
                            type="password" placeholder="Senha" required
                        />
                        <button type='submit'>Cadastrar</button>
                    </form>
                </div>
                <div className={`${styles.formContainer} ${styles.signIn}`}>
                    <form>
                        <h1>Login</h1>
                        <div className={styles.socialIcons}>
                            <a href="#"><FaGoogle /></a>
                            <a href="#"><FaGithub /></a>
                            <a href="#"><FaFacebook /></a>
                        </div>
                        <span>ou use seu e-mail e senha</span>
                        <input
                            type="email" placeholder="E-mail" required
                        />
                        <input
                            type="password" placeholder="Senha" required
                        />
                        <a href="#">Esqueceu a sua senha ?</a>
                        <button type='submit'>Login</button>
                    </form>
                </div>
                <div className={styles.toggleContainer}>
                    <div className={styles.toggle}>
                        <div className={`${styles.togglePanel} ${styles.toggleLeft}`}>
                            <h1>Bem-vindo de volta!</h1>
                            <p>Insira seus dados para usar todos os recursos do site</p>
                            <button
                                className={styles.hidden}
                                id="login"
                                ref={loginBtnRef}
                            >
                                Login
                            </button>
                        </div>
                        <div className={`${styles.togglePanel} ${styles.toggleRight}`}>
                            <h1>A paz, amigo!</h1>
                            <p>Registre-se com seus dados pessoais para usar todos os recursos do site</p>
                            <button
                                className={styles.hidden}
                                id="register"
                                ref={registerBtnRef}
                            >
                                Cadastre-se
                            </button>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    )
}

export default FormsComponent;

// frontend/src/app/forms/forms.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { NG_ICON_DIRECTIVES, provideIcons } from '@ng-icons/core';
import { bootstrapGoogle } from '@ng-icons/bootstrap-icons';
import { bootstrapFacebook } from '@ng-icons/bootstrap-icons';
import { bootstrapTwitter } from '@ng-icons/bootstrap-icons';


@Component({
  selector: 'app-forms',
  standalone: true,
  imports: [NG_ICON_DIRECTIVES],
  providers: [
    provideIcons({bootstrapGoogle, bootstrapFacebook, bootstrapTwitter})
  ],
  templateUrl: './forms.component.html',
  styleUrl: './forms.component.css'
})
export class FormsComponent {
  @ViewChild('containerElement') containerElement!: ElementRef;

  register() {
    this.containerElement.nativeElement.classList.add('active');
  }
  login() {
    this.containerElement.nativeElement.classList.remove('active');
  }
}

<main>
    <section class="container" #containerElement id="container">
        <div class="form-container sign-up">
            <form (submit)="register()">
                <h1>Cadastre-se</h1>
                <div class="social-icons">
                    <a href="#"> <ng-icon name="bootstrapGoogle"></ng-icon> </a>
                    <a href="#"> <ng-icon name="bootstrapFacebook"></ng-icon> </a>
                    <a href="#"> <ng-icon name="bootstrapTwitter"></ng-icon> </a>
                </div>
                <span>ou use seu e-mail para cadastro</span>
                <input type="text" id="username" (ngModel)="user.username" required placeholder="Nome de usuário">
                <input type="email" id="email1" (ngModel)="user.email" required placeholder="E-mail">
                <input type="password" id="password1" (ngModel)="user.password" required placeholder="Senha">
                <button (click)="registerBtn()">Cadastrar</button>
            </form>
        </div>

        <div class="form-container sign-in">
            <form (submit)="login()">
                <h1>Login</h1>
                <div class="social-icons">
                    <a href="#"> <ng-icon name="bootstrapGoogle"></ng-icon> </a>
                    <a href="#"> <ng-icon name="bootstrapFacebook"></ng-icon> </a>
                    <a href="#"> <ng-icon name="bootstrapTwitter"></ng-icon> </a>
                </div>
                <span>ou use seu e-mail e senha</span>
                <input type="email" id="email2" (ngModel)="user.email" required placeholder="E-mail">
                <input type="password" id="password2" (ngModel)="user.password" required placeholder="Senha">
                <a href="#">Esqueceu a sua senha ?</a>
                <button>Login</button>
            </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>Bem-vindo de volta!</h1>
                    <p>Insira seus dados pessoais para usar todos os recursos do site</p>
                    <button 
                        (click)="btnLogin()"
                        class="hidden" 
                        id="login"
                    >
                        Login
                    </button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>A paz, amigo!</h1>
                    <p>Registre-se com seus dados pessoais para usar todos os recursos do site</p>
                    <button 
                        (click)="btnRegister()"
                        class="hidden" 
                        id="register"
                    >
                        Cadastre-se
                    </button>
                </div>
            </div>
        </div>
    </section>
</main>
